apiVersion: v1
kind: Service
metadata:
  name: doctor-patient-portal
spec:
  selector:
    app: doctor-patient-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

